version: "3.8"

services:
  auth-service:
    build: ./backend/auth-service
    volumes:
      - ./backend/auth-service:/app
    working_dir: /app
    command: npm run dev
    ports:
      - "3001:3001"
    environment:
      - PORT=3001

  user-service:
    build: ./backend/user-service
    volumes:
      - ./backend/user-service:/app
      - /app/node_modules
    working_dir: /app
    command: npm run dev
    ports:
      - "3002:3002"
    environment:
      - PORT=3002

  match-service:
    build: ./backend/match-service
    volumes:
      - ./backend/match-service:/app
      - /app/node_modules
    working_dir: /app
    command: npm run dev
    ports:
      - "3003:3003"
    environment:
      - PORT=3003

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx:/etc/nginx/conf.d
    ports:
      - "3000:80"
    depends_on:
      - auth-service
      - user-service
      - match-service
